### ISSUE TITLE
Adopt dp111's 6502 instruction timing suite (NMOS passes today; add fixtures, and a bare-core harness for the 65C02 coprocessor CPU)

### ISSUE THREAD

**Issue by rob-smallshire** [rob-smallshire/beebium#81]
## Summary

Dominic Plunkett (dp11 on Stardot, @dp111) has offered his 6502 instruction timing test suite: https://github.com/dp111/6502Timing (GPL-3.0, the same licence as Beebium). It times almost every 6502 instruction, documented and undocumented, against a 1 MHz 6522 VIA timer, prints any discrepancy, and reports a failure count. Beebium does not use it today; the only mentions in the tree are three comments inherited from b2's core, where undocumented-opcode variants were shaped to "make the dp111 timing test pass". b2 vendors the suite and runs it in its own tests, but our bus stretching, VIA and machine assembly are our own, so b2 passing says nothing about us.

## First results (2026-09-18, master a00e719b, Model B, MOS 1.20)

| Image | Result | Emulated time |
|---|---|---|
| `6502timing.ssd` | `Number of failures : 0x00` | 4.0 s |
| `6502timing1M.ssd` (absolute addresses at &FCFE to provoke 1 MHz cycle stretching) | `Number of failures : 0x00` | 4.0 s |

Run by `*RUN 6502tim` from the disc; the failure count was also read from zero page &7A (`passfailzp`). The 1 MHz variant is the more valuable pass, since cycle stretching is Beebium's own code.

## Proposed

1. **Adopt the two NMOS images as fixtures** (`tests/assets/discs/`, with provenance, version 0.24 and SHA-256 in the README there) and add a Python scenario test per image: `*RUN 6502tim`, wait for the prompt, assert the failure count is 0 and that the screen shows no error lines. About four emulated seconds each. Passing today, so a regression guard for the core, the VIA timer and the 1 MHz stretch.
2. **Trap the documented result register.** The suite writes the failure count to &FCD0 "so emulators can trap writes to this address". A C++ test can do that directly through a 1 MHz bus write hook, without the Python client or screen scraping.
3. **Cover the CMOS core used by the Tube coprocessors.** `65C02timing.ssd` targets a BBC whose *host* CPU has been upgraded to a 65C02, which Beebium has no machine variant for, and the coprocessors have no VIA to time against. But the repository also ships vector builds (`65C02timing.6502`, `6502timing.6502`) with a documented vector table (&2010 print character, &2020 initialise, &2030 start timer with A, &2040 read timer into X, &2050 end of tests with the failure count in A). A C++ harness can load the vector build into a bare core with a flat memory, implement the timer by counting cycles, and run the Rockwell 65C02 configuration that `acorn-65c02-coprocessor` and `acorn-65c102-coprocessor` use. That directly checks the instruction cycle counts that the #70 board-timing work assumed to be right, and would do the same for the NMOS configuration without a whole machine.
4. `65C12timing*.ssd` when a Master series machine exists.
5. Credit Dominic Plunkett in the README acknowledgements when the suite is adopted.

## Notes

- Not yet checked by the suite, per its README: BRK and the HALT (jam) instructions. The reset and jam behaviour fixed in #78 and #79 is therefore outside it.
- b2's harness for reference: `src/beeb/tests/test_beeb.cpp`, class `dp111TimingTest`, which loads the image, pastes `*RUN 6502tim`, hooks &FCD0 and asserts zero failures.

**Comment by rob-smallshire** [comment]
## Adopted

On master in 09411614, 70bafd4d, 701acb66, 2b445b07 and 60b72d0a. Awaiting push. Tests, fixtures and docs only: no production code, no protocol change.

**Fixtures**, fetched from https://github.com/dp111/6502Timing at pinned commit `2cb005d7c04eee011c43e0954d9243dcfc4f5ffb` (v0.24, GPL-3.0), with provenance and SHA-256 recorded in the asset READMEs; no submodule: `tests/assets/discs/6502timing.ssd`, `6502timing1M.ssd`, and the vector builds `tests/assets/6502timing/6502timing.6502`, `65C02timing.6502`.

**Results**

| Target | Image | Result |
|---|---|---|
| Model B whole machine (MOS 1.20, DFS 2.26) | `6502timing.ssd` | 0 failures |
| Model B whole machine | `6502timing1M.ssd` (provokes 1 MHz stretching) | 0 failures |
| Bare NMOS core | `6502timing.6502` | 0 failures, agrees with the whole machine |
| Bare Rockwell 65C02 core (the coprocessor plugins' configuration) | `65C02timing.6502` | 0 failures |

The Rockwell pass independently confirms the instruction cycle counts that the #70 board-timing model relies on.

**Tests**
- `tests/test_dp111_timing_fcd0.cpp`: autoboots each disc on a Model B and traps the suite's result write to &FCD0 with a write watchpoint (existing API; nothing added to production code), asserting 0.
- `clients/beebium-python-client/tests/test_dp111_timing.py`: `*RUN 6502tim` on each image; asserts "Number of failures : 0x00" on screen and &7A == 0, printing the whole screen on failure since the suite names each mistimed instruction.
- `tests/test_6502_dp111_timing.cpp`: a bare-core harness for the vector builds. It keeps the suite's own start/stop vector code executing, so their cycles remain part of the suite's calibration, and models only VIA timer 1 behind &FE64/&FE65: one VIA tick per two CPU cycles, matching the `LSR A` on load and `ASL A` on read in the suite's vectors. The timer phase is 0 with no tuning, pinned by the suite's own "Timer Zero Error" probe.
- **Negative control:** with the timer perturbed by exactly one tick the suite completes and reports 99 failures (NMOS) and 100 (Rockwell), and prints its zero-error warning, so the harness demonstrably detects a one-cycle error and a zero is meaningful.

**Finding, left alone deliberately.** The generic `M6502_cmos6502_config` cannot run the 65C02 build: it does not implement the Rockwell bit instructions (RMB/SMB/BBR/BBS) and decodes their opcode slots as CMOS NOPs of a different length, so the three-byte BBR/BBS branches desync the instruction stream and the suite never reports. That is a configuration-scope mismatch, not a timing defect; the coprocessors use the Rockwell configuration, which passes.

**Not covered by the suite**, per its README: BRK and the jam (HALT) opcodes, so the reset and halt behaviour of #78 and #79 is outside it. `65C12timing*.ssd` waits for a Master-series machine.

Dominic Plunkett is credited in the README acknowledgements. Acceptance: full ctest 3025 of 3025; whole Python integration green.

**Comment by rob-smallshire** [comment]
Pushed to master (a00e719b..fd7ab0ba); see the adoption report above.
